### ISSUE TITLE
Build: Adding CI for validating coding style

### ISSUE THREAD

**Issue by josix** [pycontw/session-video-publisher#8]
There is no automatic coding style checking after the PR is created. Therefore, we should build a CI flow for checking the update in each PR if conform to the style by using tools like `isort`, `black`. Moreover, adding type checking flow by using `mypy` also cloud be included here.

**Comment by uranusjr** [comment]
The most popular configuration in recent times is to set up pre-commit and use pre-commit.ci to run the checks. We should probably add Black, Flake8, Mypy, and a few simple ones like trailing-whitespace. [pip’s configuration is a good example](https://github.com/pypa/pip/blob/main/.pre-commit-config.yaml).

**Comment by gary9630** [comment]
@josix I am interested in this issue, please add me into the working group if possible.

**Comment by josix** [comment]
Is it better solution to use [cruft](https://github.com/cruft/cruft) and [Python project template](https://github.com/Lee-W/cookiecutter-python-template) for importing related tools and GitHub Actions that handle this issue? Or it is just over-engineering.
